export const START_FETCHING_SCHEMAS = 'START_FETCHING_SCHEMAS';
export const RESOLVE_FETCHING_SCHEMAS = 'RESOLVE_FETCHING_SCHEMAS';
export const REJECT_FETCHING_SCHEMAS = 'REJECT_FETCHING_SCHEMAS';

export const START_INVOKING = 'START_INVOKING';
export const RESOLVE_INVOKING = 'RESOLVE_INVOKING';
export const REJECT_INVOKING = 'REJECT_INVOKING';
export const REJECT_ERROR = 'REJECT_ERROR';
