import React from 'react';
import Chip from 'material-ui/Chip';
import Switch from 'material-ui/Switch';
import Select from 'material-ui/Select';
import TextField from 'material-ui/TextField';
import { MenuItem } from 'material-ui/Menu';
import { DateTimePicker } from 'material-ui-pickers';
import ArrowLeft from 'material-ui-icons/KeyboardArrowLeft';
import ArrowRight from 'material-ui-icons/KeyboardArrowRight';
import Check from 'material-ui-icons/Check';


export default register => {
  register.grid.bool(({ value }) => (value ? <Check /> : ''));
  register.grid.enum(({ value }) => <Chip label={value} />);
  register.grid.date(({ value }) => new Date(value).toLocaleString());
  register.grid.any(({ value }) => value);

  register.editor.bool(({ value, schema, propertyName, onChange }) => (
    <Switch
      checked={value}
      disabled={schema[propertyName].autoGenerated}
      onChange={evt => onChange(evt.target.checked)}
    />
  ));

/*   register.editor.date(({ value, schema, propertyName, onChange }) => (
    <DateTimePicker
      value={value ? new Date(value) : null}
      onChange={value => onChange(value.toISOString())}
      disabled={schema[propertyName].autoGenerated}
      leftArrowIcon={<ArrowLeft />}
      rightArrowIcon={<ArrowRight />}
    />
  )); */

  register.editor.enum(({ value, onChange, schema, propertyName }) => (
    <Select value={value} onChange={evt => onChange(evt.target.value)}>
      {schema[propertyName].values.map(v => (
        <MenuItem key={v} value={v}>
          {v}
        </MenuItem>
      ))}
    </Select>
  ));

  register.editor.number(({ propertyName, value, onChange, schema }) => (
    <TextField
      name={propertyName}
      type="number"
      value={value}
      onChange={evt => onChange(Number(evt.target.value))}
      disabled={schema[propertyName].autoGenerated}
    />
  ));

  register.editor.string(({ propertyName, value, onChange, schema }) => (
    <TextField
      name={propertyName}
      value={value}
      onChange={evt => onChange(evt.target.value)}
      disabled={schema[propertyName].autoGenerated}
    />
  ));

  register.editor.any(({ value }) => value || null);
};
