export const TOGGLE_FETCHING = 'START_FETCHING';
export const REJECT_ERROR = 'REJECT_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const RESOLVE_FETCHING_SCHEMAS = 'RESOLVE_FETCHING_SCHEMAS';
export const RESOLVE_FETCHING_ITEMS = 'RESOLVE_FETCHING_ITEMS';
export const RESOLVE_FETCHING_ITEM = 'RESOLVE_FETCHING_ITEM';
export const RESOLVE_UPDATING_ITEM = 'RESOLVE_UPDATING_ITEM';
