export const START_FETCHING_ENTITIES = Symbol('START_FETCHING_ENTITIES');
export const RESOLVE_FETCHING_ENTITIES = Symbol('RESOLVE_FETCHING_ENTITIES');
export const REJECT_FETCHING_ENTITIES = Symbol('REJECT_FETCHING_ENTITIES');

export const START_INVOKING = Symbol('START_INVOKING');
export const RESOLVE_INVOKING = Symbol('RESOLVE_INVOKING');
export const REJECT_INVOKING = Symbol('REJECT_INVOKING');
